# Generated by Django 5.2.4 on 2025-07-25 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_anon',
            field=models.BooleanField(default=False),
        ),
    ]
