# Generated by Django 5.2.4 on 2025-07-25 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_is_anon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='is_anon',
            new_name='anonymous',
        ),
    ]
