# Generated by Django 5.2.4 on 2025-08-06 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_userprofile_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='prof_theme',
            field=models.TextField(blank=True, default='light'),
        ),
    ]
