# Generated by Django 5.2.4 on 2025-08-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_themes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='allowed_themes',
            field=models.ManyToManyField(blank=True, to='user_profile.themes'),
        ),
    ]
