# Generated by Django 5.2.4 on 2025-08-13 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_allowed_themes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='allowed_themes',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='themes',
            field=models.ManyToManyField(blank=True, to='user_profile.theme'),
        ),
        migrations.DeleteModel(
            name='Themes',
        ),
    ]
