# Generated by Django 5.2.4 on 2025-08-13 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0006_theme_remove_userprofile_allowed_themes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='slug',
        ),
    ]
