# Generated by Django 5.2.5 on 2025-08-25 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_remove_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='group',
            field=models.CharField(default='User', max_length=50),
            preserve_default=False,
        ),
    ]
